/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-2',
  aws_cognito_region: 'eu-west-2',
  aws_user_pools_id: 'eu-west-2_fpH3cOgED',
  aws_user_pools_web_client_id: '197gmms54dmskurhnh8l2q7qta',
  oauth: {},
};

export default awsmobile;
