/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-2',
  aws_cognito_region: 'eu-west-2',
  aws_user_pools_id: 'eu-west-2_e1wu3D067',
  aws_user_pools_web_client_id: '28mmdb4pu0bb5p6tgvun6utfv5',
  oauth: {},
};

export default awsmobile;
